# Generated by Django 5.2.13 on 2026-05-23 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('unit', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro')], default='unidad', max_length=20, verbose_name='Unidad')),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock actual')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock mínimo (alerta)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de costo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Artículo de inventario',
                'verbose_name_plural': 'Artículos de inventario',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='inventory_stock_gte_0'), models.CheckConstraint(condition=models.Q(('min_stock__gte', 0)), name='inventory_min_stock_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('adjustment', 'Ajuste')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad')),
                ('notes', models.TextField(blank=True, verbose_name='Referencia / motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem', verbose_name='Artículo')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ('-created_at',),
            },
        ),
    ]
