# Generated by Django 5.2.13 on 2026-05-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='dish_price_gte_0'),
        ),
    ]
