# Generated by Django 5.2.13 on 2026-05-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_dish_price_gte_0'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orderitem_quantity_gt_0'),
        ),
    ]
