# Generated by Django 5.2.13 on 2026-05-23 17:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_discount_amount_order_promotion_order_subtotal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_type', models.CharField(choices=[('boleta', 'Boleta de venta'), ('factura', 'Factura')], default='boleta', max_length=20, verbose_name='Tipo de comprobante')),
                ('series', models.CharField(default='B001', max_length=4, verbose_name='Serie')),
                ('correlative', models.PositiveIntegerField(verbose_name='Correlativo')),
                ('receptor_name', models.CharField(max_length=255, verbose_name='Nombre / Razón social')),
                ('receptor_doc', models.CharField(blank=True, max_length=20, verbose_name='DNI / RUC')),
                ('receptor_address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('receptor_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo del receptor')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IGV (18%)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ('-created_at',),
                'unique_together': {('series', 'correlative')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal línea')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice', verbose_name='Comprobante')),
            ],
            options={
                'verbose_name': 'Línea de comprobante',
                'verbose_name_plural': 'Líneas de comprobante',
            },
        ),
    ]
