# Generated by Django 5.2.13 on 2026-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percentage', max_length=20, verbose_name='Tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del descuento')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto mínimo de pedido')),
                ('starts_at', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('ends_at', models.DateTimeField(verbose_name='Fecha de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite de usos')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Veces utilizada')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ('-starts_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='promotion_discount_gt_0')],
            },
        ),
    ]
