# Generated by Django 5.2.13 on 2026-07-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('in_progress', 'En progreso'), ('resolved', 'Resuelta'), ('closed', 'Cerrada')], default='new', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reclamación',
                'verbose_name_plural': 'Reclamaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('order_created', 'Orden creada'), ('order_updated', 'Orden actualizada'), ('order_completed', 'Orden completada'), ('reservation_created', 'Reserva creada'), ('reservation_updated', 'Reserva actualizada'), ('reservation_cancelled', 'Reserva cancelada'), ('login', 'Acceso'), ('logout', 'Cierre de sesión'), ('admin_action', 'Acción de admin')], max_length=50)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='support_act_created_3b5dd4_idx'), models.Index(fields=['action'], name='support_act_action_628c26_idx')],
            },
        ),
    ]
