# Generated by Django 5.2.13 on 2026-07-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
