# Generated by Django 5.2.13 on 2026-07-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_activitylog_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='resource_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
